server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/SpringCloud/native-file-repo
        git:
#          uri: file:///Users/jinheekim/Desktop/SpringCloud/git-local-repo
          uri: https://github.com/skesswswkk/spring-cloud-config.git

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh
